#ifndef CODECHECKERPLUGIN_GLOBAL_H
#define CODECHECKERPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(CODECHECKERPLUGIN_LIBRARY)
#  define CODECHECKERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CODECHECKERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CODECHECKERPLUGIN_GLOBAL_H
