/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef report_server_CONSTANTS_H
#define report_server_CONSTANTS_H

#include "report_server_types.h"



class report_serverConstants {
 public:
  report_serverConstants();

  int64_t MAX_QUERY_SIZE;
};

extern const report_serverConstants g_report_server_constants;



#endif
