/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "report_server_constants.h"



const report_serverConstants g_report_server_constants;

report_serverConstants::report_serverConstants() {
  MAX_QUERY_SIZE = 500LL;

}



